### ISSUE TITLE
Support Bulma 0.8

### ISSUE THREAD

**Issue by kerams** [Fulma/Fulma#232] opened 2019-10-22 12:35 UTC
https://bulma.io/2019/10/15/light-dark-colors/

From the point of view of Fulma, I think 2 things are needed:
- Add new colors (`IsPrimaryLight`, `IsPrimaryDark`, etc.)
- Update Panel.panel so that the first parameter is not a list of `GenericOption`, but a list of 
 `Panel.Panel.Option`, which will be used to specify the new panel color. This is a breaking change.

The release notes also contain this:
> New features
> #2563 .image has a new .is-fullwidth modifier

**Comment by MangelMaxime** [comment] 2019-11-06 15:22
Thank you for the heads-up about upgrading the supported version :)

There is more to do than that because Fulma is currently supporting `bulma@0.7.1` so we have to provide support for all the intermediary versions. 

I am working it and should be able to release a new version during this week.

**Comment by MangelMaxime** [comment] 2019-11-07 15:08
By looking at the source code of Bulma and by testing it seems like only the `button` elements need to have the new option `IsLight`. This class is used to trigger the switch to "light" color locally.

[See](https://bulma.io/documentation/elements/button/#colors)

The other element which benefits from this new feature is `message` but from what I see it's automatically activated by default without modifications.

**Fulma documentation with bulma 0.7.1**

<img width="917" alt="Capture d’écran 2019-11-07 à 16 04 37" src="https://user-images.githubusercontent.com/4760796/68400425-527f5000-0178-11ea-84c8-b1006b74fa05.png">

**Fulma documentation with bulma 0.8.0**
<img width="1057" alt="Capture d’écran 2019-11-07 à 16 04 33" src="https://user-images.githubusercontent.com/4760796/68400465-62972f80-0178-11ea-9241-5e0601a1cf06.png">

See how the bold text is now yellow tainted instead of black.

I also tried to add classes like `is-primary-light`, `is-info-light` but it's not recognized so I will not add `IsPrimaryLight`,  `IsPrimaryDark` for now.

**Comment by kerams** [comment] 2019-11-07 15:16
Oh, it looks like you're right
>The light colors are used by the button element

That is so strange. I fully expected to be able to use the new colors universally. No idea why that isn't the case.

**Comment by MangelMaxime** [comment] 2019-11-07 15:19
I don't know either, and I had a hard time understanding what I mentioned in my comments.

I was expecting the same as you...

Perhaps, it will come later. For me, it looks like `*-light` and `-dark` is like a duplicate of `*-invert` with better default looks.

**Comment by MangelMaxime** [comment] 2019-11-07 15:35
Released in version 2.4.0 (NuGet is processing the new package)

**Closed by MangelMaxime** 2019-11-07 15:35 UTC
